version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      non-major-images:
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /ollama
    schedule:
      interval: weekly
    groups:
      non-major-ollama:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
