services:
  backend:
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !override
      - activemq
      - keycloak
      - postgres

  ollama:
    profiles:
      - docker-ollama
