services:
  backend:
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    models: !reset []
    depends_on: !override
      - activemq
      - keycloak
      - ollama
      - postgres

  ollama-dmr-adapter:
    profiles:
      - dmr

  ollama:
    image: slawekradzyminski/ollama-mock:1.0.6@sha256:bb34ad70c6673f2f384e43da2b0984bb832eee7d76ee992365a93e612133c81c
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - my-private-ntwk
