services:
  backend:
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    models: !reset []
    depends_on: !override
      - activemq
      - keycloak
      - ollama
      - postgres

  ollama-dmr-adapter:
    profiles:
      - dmr

  ollama:
    image: slawekradzyminski/ollama-mock:1.0.9@sha256:24852d0f78eb7ed208bb1eaaab1d912d29e5e74d6c28c2e6a31dd1cbcdedbdab
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - my-private-ntwk
