services:
  backend:
    image: slawekradzyminski/backend:2.3
    platform: linux/amd64
    restart: always
    ports:
      - "4001:4001"
    hostname: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my-private-ntwk

  frontend:
    image: slawekradzyminski/frontend:2.0
    platform: linux/amd64
    restart: always
    ports:
      - "8081:8081"
    hostname: frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my-private-ntwk

  activemq:
    image: apache/activemq-artemis:2.31.2
    platform: linux/amd64
    restart: always
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: "true"
      EXTRA_ARGS: --http-host 0.0.0.0 --relax-jolokia --no-autotune
      DISABLE_SECURITY: true
      BROKER_CONFIG_GLOBAL_MAX_SIZE: 512mb
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
    hostname: activemq
    networks:
      - my-private-ntwk

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    hostname: mailhog
    networks:
      - my-private-ntwk

  consumer:
    image: slawekradzyminski/consumer:1.2
    platform: linux/amd64
    restart: always
    ports:
      - "4002:4002"
    hostname: consumer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my-private-ntwk

networks:
  my-private-ntwk:
    driver: bridge
