- name: Deploy application stack
  hosts: production
  become: true
  gather_facts: true

  roles:
    - swap
    - postgres_backup
    - role: deployment_silence
      deployment_silence_state: present
    - app
    - verify
    - role: deployment_silence
      deployment_silence_state: absent
    - cleanup
